### ISSUE TITLE
Reorder parameters in seas() to put `x` first.

### ISSUE THREAD

**Issue by lianos** [lianos/sparrow#5]
This function is really polymorphic over `x`, so this should come first.

The current function signature is:

```r
seas <- function(gdb, x, design, contrast, ...)
```

but should really by

```r
seas <- function(x, gdb, design = NULL, contrast = NULL, ...)
```

Let's bite this bullet before we release this into the wild.

**Comment by carroj11** [comment]
Some fallout from this is that you also need to reorder any unnamed (by-position) arguments when calling `seas()`. This conversion is as above

https://github.com/lianos/multiGSEA/blob/85719e2b5388d425a3182c8611989a4b95fb75d1/R/multiGSEA.R#L162

https://github.com/lianos/sparrow/blob/9042f1609055e87cefad4033ac783603d947fc91/R/seas.R#L187

but now the calls to these are yet to be changed

https://github.com/lianos/multiGSEA.shiny/blob/ef24e4dda17ec6a79928e9cf7da7da57b5ee57eb/R/shiny-MultiGSEAResultContainer.R#L20

https://github.com/lianos/sparrow.shiny/blob/b536b6c307f49258adccd1275260313e074c67c5/R/shiny-SparrowResultContainer.R#L20

(image, since GH won't let me inline multiple sources)

![multiGSEA_to_sparrow](https://user-images.githubusercontent.com/88032988/129143519-56c056e9-ce5f-47ef-a014-6a119713688c.jpg)

This seems to cause some breakage.

**Comment by jonocarroll** [comment]
(back to my public account...) it appears the fix was all that was needed and we're successfully migrating. Thanks for the lightning fast patch ⚡ !
